### ISSUE TITLE
Update for new API calls?

### ISSUE THREAD

**Issue by matt-matt2** [yoke88/PSPHPIPAM#1]
Is anyone working on updates to support new API calls?

**Comment by matt-matt2** [comment]
(this is the quietest github issues list I've ever seen..)

**Comment by leoessabba** [comment]
I was using this, but since we updated to 1.31 version, we have issues. Could someone update this , please? Thank you!

**Comment by yoke88** [comment]
can you post your issues ? for example:
the details of error message and the command you use

**Comment by leoessabba** [comment]
Thanks for your attention.

Acctually, I could fix the problem changing a tiny detail. Insted of using:

$ApiUrl = 'https://phpipam.test/phpipam/api/
I changed it to:
$ApiUrl = 'https://phpipam.test/phpipam/api/index.php'

Now it is ok. Sorry to bother you.

**Comment by matt-matt2** [comment]
Hmm. I'm now seeing failures setting up a session. I would imagine that like the above user these failures came in at the upgrade to v1.3.1.

The above "URL fix" doesn't seem to work for me. The API key and paths are still valid in the web UI. I'll try some manual commands to look at this in more detail when I get a chance.


New-PhpIpamSession : Exception of type 'Microsoft.PowerShell.Commands.WriteErrorException' was thrown.
At D:\Scripts\IPAM\check_ipam.ps1:21 char:11
+ $result = New-PhpIpamSession -useAppKeyAuth -PhpIpamApiUrl "$ApiUrl" -AppID "$Ap ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-PhpIpamSession

**Comment by yoke88** [comment]
New-PhpIpamSession support  debug  switch ,you can turn it on to see what is going wrong

`New-PhpIpamSession -useAppKeyAuth -PhpIpamApiUrl https://<redact>/phpipam/api/ -AppID deployment -AppKey <redact>  -debug`

**Comment by matt-matt2** [comment]
The -debug flag does not help in this instance, but I stepped through the code with the debugger and got a trap in PhpIpamBaseFunctions line 381 during the call to:

                $r=Invoke-RestMethod -Method get -Uri $uri 

The error message that comes up actually refers to the call to "write-error" following the {catch} on line 393.

Up to this point I can't see any issues with the uri construction. There's no output from adding "-Debug" to this command. Any thoughts? I'll continue looking around..

**Comment by matt-matt2** [comment]
Know what I figured it out .. turns out someone had put a redirect-to-https in the IPAM web server config and the self signed cert was not trusted. Drop it back to http:// and it's working fine again. Sorry for the noise ..

**Comment by yoke88** [comment]
thanks for the feedback and the root cause you found,good work.

invoke-webrequest has no switch to ignore ssl trust now, so if you want use ssl , using cert signed by your enterprise ca or public ca.
________________________________
