### ISSUE TITLE
problem using crypto

### ISSUE THREAD

**Issue by MartinEtcheverry** [yoke88/PSPHPIPAM#11]
Hi i am running this :
New-PhpIpamSession -useAppKeyAuth -PhpIpamApiUrl http://192.168.1.23/api/myapp/user -appid script -appkey '76c9b896c4b48f12b51824952****'

And get this error:
New-PhpIpamSession : Cannot validate argument on parameter 'AppKey'. The argument "76c9b896c4b48f12b51824952****" does not match the "^[0-9a-fA-f]{32}$"

**Comment by yoke88** [comment]
appkey is 32 length, i do not know whether the new version has changed the appkey length

?取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MartinEtcheverry** [comment]
thank you , the problem was a error in the appkey
