### ISSUE TITLE
remove IP address

### ISSUE THREAD

**Issue by evkogan1** [yoke88/PSPHPIPAM#13]
Hi.
I can't search how to delete the IP address.
Can help?

**Comment by yoke88** [comment]
Remove-PhpIpamAddressByID

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by evkogan1** [comment]
I update files. Then can't find this function.
But in Addresses.ps1 this function  present 
---------------------------------
PS C:\> Get-Command -Module PSPHPIPAM

CommandType     Name                                               Version    Source                                                                                                                                                                             
-----------     ----                                               -------    ------                                                                                                                                                                             
Function        Convert-IdentifiersArrayToHashTable                1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        ConvertTo-HashtableFromPsCustomObject              1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        ConvertTo-PsCustomObjectFromHashtable              1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Expand-PhpIpamTokenLife                            1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Get-PhpIpamAddresses                               1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Get-PhpIpamAddressesByID                           1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Get-PhpIpamAddressesByIP                           1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Get-PhpIpamAllSections                             1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        get-phpipamAllSubnets                              1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Get-PhpIpamSectionByName                           1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Get-PhpIpamSectionsByID                            1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Get-PhpIpamSubnetAddressesByID                     1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Get-PhpIpamSubnetByID                              1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Get-PhpIpamSubnetFirst_freeByID                    1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Get-PhpIpamSubnetsBySectionID                      1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Get-PhpIpamSubnetSlaves_RecursiveByID              1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Get-PhpIpamSubnetSlavesByID                        1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Get-PhpIpamSubnetUsageByID                         1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Invoke-PhpIpamExecute                              1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        new-phpipamAddress                                 1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        New-PhpIpamSection                                 1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        New-PhpIpamSession                                 1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        New-PhpIpamSubnet                                  1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Protect-Rijndael256ECB                             1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Remove-PhpIpamSection                              1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Remove-PhpIpamSession                              1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Remove-PhpIpamSubnetAllAddressBySubnetID           1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Remove-PhpIpamSubnetAllPermissionsBySubnetID       1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Remove-PhpIpamSubnetByID                           1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Search-PhpIpamAddressByHostname                    1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Test-PhpIpamToken                                  1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        UnProtect-Rijndael256ECB                           1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Update-PhpIpamAddressByID                          1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Update-PhpIpamSection                              1.0.1      PSPHPIPAM                                                                                                                                                                          
Function        Update-PhpIpamSubnet                               1.0.1      PSPHPIPAM                                                                                                                                                                          
---------------------------

**Comment by yoke88** [comment]
I have downloaded the PS module from github and did a test , there was no problem like yours.

![批注 2019-04-26 084957](https://user-images.githubusercontent.com/3146226/56776694-4ea16700-6800-11e9-92fb-91b1e67eab8a.jpg)

**Comment by yoke88** [comment]
try the command below to see the file is up to date.

**Comment by evkogan1** [comment]
Thank. I understood. ISE Reload helped
