### ISSUE TITLE
Additional check in Disable-CertsCheck.ps1 ('TrustAllCertsPolicy' already exists)

### ISSUE THREAD

**Issue by Batkovyu** [yoke88/PSPHPIPAM#20]
Hello,

My script already disables cert check at the beginning in the same way.
Later, in the middle of the script, I try to import the PSPHPIPAM module and receive the error below:

```
add-type : Cannot add type. The type name 'TrustAllCertsPolicy' already exists.
At C:\Program 
Files\WindowsPowerShell\Modules\PSPHPIPAM\1.3.2\Functions\Private\Disable-CertsCheck.ps1:14 char:9
```

Is it possible to add one additional check for this type? Something like this:

```
if (-not ("TrustAllCertsPolicy" -as [type])) {
        Add-Type ...
        [System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy
}
```

**Comment by yoke88** [comment]
fixed in [da894dc
](https://github.com/yoke88/PSPHPIPAM/commit/da894dc014e074764dc430e89e1ac3c495c19d4d)
