### ISSUE TITLE
Question - First available subnet within selected for mask

### ISSUE THREAD

**Issue by Grant-Rc** [yoke88/PSPHPIPAM#29]
Hello guys, 

We used to be able to get the next free subnet and then use that to create a new one by using the command 

Get-PhpIpamSubnetfirst_subnetByID

I got my laptop rebuild and after reinstalling everything including this module again I noticed this is no longer a function

I have recreated the function but is there a reason it was removed?

`
$cred = Get-Credential

$PhpIpamApiUrl = "https://<IPAM_Server>/api"
$AppID = "<API token>"

    $headers = @{
        Authorization = "Basic {0}" -f $base64Token
    }
    $uri = "{0}/{1}/user/" -f $PhpIpamApiUrl, $AppID

$token = Invoke-RestMethod -Method post -Uri $uri -SkipCertificateCheck -Credential $cred -SkipHeaderValidation -Authentication Basic

$headers = @{
    token = $token.data.token     
}

Invoke-RestMethod -Method get -Uri "https://{IPAM_Server}/api/{AppID}/subnets/{ID}/first_subnet/{mask}/" -Headers $headers -SkipCertificateCheck
`

**Comment by yoke88** [comment]
see the function here

https://github.com/yoke88/PSPHPIPAM/blob/master/PSPHPIPAM/Functions/Public/Subnets/Get-PhpIpamSubnetFirstFreeByID.ps1

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Grant Crowe ***@***.***>
Sent: Wednesday, June 14, 2023 9:03:17 AM
To: yoke88/PSPHPIPAM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [yoke88/PSPHPIPAM] Question - (Issue #29)


Hello guys,

We used to be able to get the next free subnet and then use that to create a new one by using the command

Get-PhpIpamSubnetfirst_subnetByID

I got my laptop rebuild and after reinstalling everything including this module again I noticed this is no longer a function

I have recreated the function but is there a reason it was removed?

`$cred = Get-Credential

$PhpIpamApiUrl = "https://<IPAM_Server>/api"
$AppID = ""

$headers = @{
    Authorization = "Basic {0}" -f $base64Token
}
$uri = "{0}/{1}/user/" -f $PhpIpamApiUrl, $AppID


$token = Invoke-RestMethod -Method post -Uri $uri -SkipCertificateCheck -Credential $cred -SkipHeaderValidation -Authentication Basic

$headers = @{
token = $token.data.token
}

Invoke-RestMethod -Method get -Uri "https://davpipam001/api/Powershell/subnets/628/first_subnet/24/" -Headers $headers -SkipCertificateCheck
`

―

**Comment by Grant-Rc** [comment]
Thank you for the reply @Yoke88 but unless this is a bug this only returns the first IPaddress not the first subnet 

`Get-PhpIpamSubnetFirstFreeByID -ID 625 -debug
DEBUG: Using TokenAuth,Test Token Status
DEBUG: IsStaticToken=False
DEBUG: get uri=https://{server}/api/{App}/subnets/625/first_free/
DEBUG: headers={
  "token": ""
}
DEBUG: contentType=null
DEBUG: body={}
DEBUG: Func Return:
{
  "code": 409,
  "success": false,
  "message": "Subnet contains subnets",
  "time": 0.007
}
`

This is because its using the API call 

`/api/my_app/subnets/{id}/first_free/ | Returns first available IP address in subnet
`

whereas the old one I assume was 

`/api/my_app/subnets/{id}/first_subnet/{mask}/ | Returns first available subnet within selected for mask`

**Comment by yoke88** [comment]
you can create your own funtion or just using Invoke-PhpIpamExecute

$r=Invoke-PhpIpamExecute -method get -controller subnets -identifiers @($ID,"first_free")
        Resolve-PhpIpamExecuteResult -result $r


获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yoke88** [comment]
$r=Invoke-PhpIpamExecute -method get -controller subnets -identifiers @($ID,"first_subnet",$mask)

Resolve-PhpIpamExecuteResult -result $r

# according the api here
/api/my_app/subnets/{id}/first_subnet/{mask}/   Returns first available subnet within selected for mask


获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
