### ISSUE TITLE
Just getting generic error when trying to start phpIpam session

### ISSUE THREAD

**Issue by rychannel** [yoke88/PSPHPIPAM#3]
`Import-Module PSPHPIPAM

new-PhpIpamSession -useAppkeyAuth -phpIpamApiURL 'https://ipam.woodmen.net/phpipam/api/' -AppID powershell -AppKey <redact>
`

All I get is the following error... doesn't give a clue where to start troubleshooting...

`new-PhpIpamSession : Exception of type 'Microsoft.PowerShell.Commands.WriteErrorException' was thrown.
At H:\windows_scripts\phpipam\phpipam-cheat.ps1:19 char:1
+ new-PhpIpamSession -useAppkeyAuth -phpIpamApiURL 'https://ipam.woodme ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-PhpIpamSession`

**Comment by yoke88** [comment]
Using -debug switch to see what's going on

?取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rychannel** [comment]
-debug doesn’t return anything extra   
  

  
  

  
  
>

**Comment by yoke88** [comment]
I have noticed that your url was https based, maybe the ca is nit trust, change to http and try?

Invoke-webrest does not have a switch to ignore untrust cert

?取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yoke88** [comment]
My typo, invoke-restmethod does not have a switch to ignore untrust cert before powershell 6, there may be some hacks there, i will try to test this.



https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-6

?取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yoke88** [comment]
close #2
