### ISSUE TITLE
Invalid enc_request

### ISSUE THREAD

**Issue by auchri** [yoke88/PSPHPIPAM#4]
Hi,

I tried your PS library for phpIpam and I get the following error:

```
New-PhpIpamSession : {"code":503,"success":0,"message":"Invalid enc_request","time":0.001}
In C:\Users\foo\Desktop\ipam\test.ps1:4 Zeichen:1
+ New-PhpIpamSession -useAppKeyAuth -PhpIpamApiUrl 'https://ipam ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-PhpIpamSession
```

The full url is `https://ipam/api/?app_id=43543&enc_request=zLXkPGhy9VpOI2HpkZ8dpoZXDXtd60fbLRKk1z10R7c%3d`

**Comment by yoke88** [comment]
Check your appid and keys

________________________________

**Comment by auchri** [comment]
They are correct. It doesnt work because phpipam switched to openssl -> https://github.com/phpipam/phpipam/issues/2316#issuecomment-439944610

I've implemented the new auth mechanism already, so I'm closing this.
