### ISSUE TITLE
Example for new-phpipamAddress

### ISSUE THREAD

**Issue by GalipoliX** [yoke88/PSPHPIPAM#5]
Hi,
i am having trouble understanding what params to pass to the "new-phpipamAddress" function.
Could you please give an example for this ?

Also, how am i supposed to get the SubnetID for the ip address to register ?
I only have "Get-PhpIpamSubnetByID". A function "Get-PhpIpamSubnetByIP" would be really helpful.

Thanks
Best regards!

**Comment by yoke88** [comment]
It all depends on the api which PSPHP provides , i have no time to implement all the apis ,but you can study from the funtions which had been implemented in powershell

?取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yoke88** [comment]
Readme will give you a glue.
See the screenshot below ,you can use invoke-phpipamexecute to implement your own function

[图像]




获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yoke88** [comment]
This document provide the list of parameters which a controller can use

https://phpipam.net/api/

________________________________

**Comment by yoke88** [comment]
Ok , i will give a short introduction.

the main function in this module  is Invoke-PhpIpamExecute, if you have read the help of Invoke-PhpIpamExecute , you will get some glue.

``` powershell
      .PARAMETER $controller
      Api Endpoint you want use ,which can be one of such set
      ("sections","subnets","folders","addresses","vlans","l2domains","vfr","tools","prefix")
      .PARAMETER $identifiers
      Array to idenfify a resource
      if the api url is  /api/my_app/sections/{id}/subnets/, the identifiers array will be @(4,'subnets'), 4 is the section which id is 4
      .PARAMETR $params
      Hashtable to specify the query string. if the api url you want query is  /api/my_app/sections/ and then you specify @{id=1} as $params
      the result with return just one section which id is 1.
      .PARAMETER $headers
      you can specify you own headers here.
      .PARAMETER $contentType
      specify your contenType
``` 

the params parameter can be a hashtable or a pscustomobject.

for example:
```powershell
$params=@{


}
```

but what is the valid params should i use , you must refer the PHPIPAM API https://phpipam.net/api/

Parameter | Type | Methods | Description
-- | -- | -- | --
id | number | GET, PATCH, DELETE | address identifier, identifies which addressto work on.
subnetId | number | POST | Id of subnet address belongs to
ip | ip | POST | IP address
is_gateway | binary | POST, PATCH | Defines if address is presented as gateway
description | text | POST, PATCH | Address description
hostname | varchar | POST, PATCH | Address hostname
mac | varchar | POST, PATCH | Mac address
owner | varchar | POST, PATCH | Address owner
tag | int | POST, PATCH | IP tag (online, offline, …)
PTRignore | binary | POST, PATCH | Controls if PTR should not be created
PTR | int | POST, PATCH | Id of PowerDNS PTR record
deviceId | int | POST, PATCH | Id of device address belongs to
port | varchar | POST, PATCH | Port
note | text | POST, PATCH | Note
lastSeen | datetime | POST, PATCH | Date and time address was last seen with ping.
excludePing | binary | POST, PATCH | Exclude this address from status update scans (ping)
editDate | datetime | / | Date and time of last update


Or if you are lazy like me ,you can using get-psphpipamaddress* function to return a address object ,and remove the non necessary properies and change some properies ,than post it ( you must convert it to a hashtable or a pscustomobject first)

**Comment by GalipoliX** [comment]
Thanks this helped me a lot !
